//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpTemplate.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CriarTarefasQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CriarTarefasQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpTemplate.Queries.CriarTarefasQueries", typeof(CriarTarefasQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_bug_text_table (id,description,steps_to_reproduce,additional_information) VALUES(1,&apos;Teste Descricao&apos;,&apos;reproduz&apos;, &apos;informaçoes&apos;);.
        /// </summary>
        internal static string MassaDeDadosAdicionarMarcadores {
            get {
                return ResourceManager.GetString("MassaDeDadosAdicionarMarcadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_bug_table (project_id,reporter_id,handler_id,duplicate_id,priority,severity,reproducibility,STATUS,resolution,projection,
        ///eta,bug_text_id,os,os_build,platform,version,fixed_in_version,build,profile_id,view_state,summary,sponsorship_total,sticky,target_version,
        ///category_id)VALUES(1,1,0,0,30,50,70,10,10,10,10,1,&apos;mj&apos;,43,&apos;MJFSS&apos;, &apos;&apos;,&apos;&apos;,&apos;&apos;,24,10,&apos;Teste&apos;, 0,0,&apos;&apos;,1);.
        /// </summary>
        internal static string MassaDeDadosCriarTarefas {
            get {
                return ResourceManager.GetString("MassaDeDadosCriarTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_tag_table (user_id,NAME,description) VALUES(1,&apos;XPTO 2019&apos;,&apos;&apos;);.
        /// </summary>
        internal static string MassaDeDadosPreencherCamposTarefa {
            get {
                return ResourceManager.GetString("MassaDeDadosPreencherCamposTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_bug_tag_table(bug_id,tag_id,user_id) VALUES (1,1,1);.
        /// </summary>
        internal static string MassaDeDadosPreencherOsCampos {
            get {
                return ResourceManager.GetString("MassaDeDadosPreencherOsCampos", resourceCulture);
            }
        }
    }
}
